name: DumbCoin
main: com.turt2live.dumbcoin.DumbCoin
version: maven-version-number
description: I hate downloading plugins.
author: turt2live
website: http://github.com/turt2live/DumbCoin
build: jenkins-build-number
softdepend: [Vault]
load: STARTUP
commands:
    money:
        aliases: [eco, bal, balance]
        usage: /<command> <playerName | pay | give | take | set | top | uuid | convert | reload> [...]
        description: Money command
permissions:
    money.balance:
        default: true
        description: Allows /money (no arguments)
    money.balance.others:
        default: op
        description: Allows /money <player name>
    money.pay:
        default: true
        description: Allows /money pay <player> <amount>
    money.give:
        default: op
        description: Allows /money give <player> <amount>
    money.take:
        default: op
        description: Allows /money take <player> <amount>
    money.set:
        default: op
        description: Allows /money set <player> <amount>
    money.top:
        default: true
        description: Allows /money top
    money.reload:
        default: op
        description: Allows /money reload
    money.import:
        default: op
        description: Allows /money import [pluginName]
    money.uuid:
        default: op
        description: Allows /money uuid
    money.convert:
        default: op
        description: Allows /money convert <yaml/mysql> <yaml/mysql>